modLoader="javafml" #mandatory
loaderVersion="[32,)" #mandatory
[[mods]] #mandatory
modId="lookatthat" #mandatory
version="1.4-1.16.1" #mandatory
displayName="Look At That" #mandatory
description='''
Look at that!
'''
[[dependencies.lookatthat]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[32,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.lookatthat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1,)"
    ordering="NONE"
    side="BOTH"
