modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory
[[mods]] #mandatory
modId="lookatthat" #mandatory
version="1.2" #mandatory
displayName="Look At That" #mandatory
description='''
Look at that!
'''
