modLoader="javafml" #mandatory
loaderVersion="[33,)" #mandatory
license="MIT"
[[mods]] #mandatory
modId="lookatthat" #mandatory
version="${version}" #mandatory
displayName="Look At That" #mandatory
description='''
Look at that!
'''
[[dependencies.lookatthat]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[33,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.lookatthat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2,)"
    ordering="NONE"
    side="BOTH"
